import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SessionProvider } from "next-auth/react";
import { auth, unstable_update } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/components/providers/Modal-provider";
import { SheetProvider } from "@/components/providers/Sheet-provider";
import { prisma } from "@/lib/prisma";
import { SiteProvider } from "@/components/providers/Site-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const site = await prisma.site.findFirst();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <ModalProvider>
            <SiteProvider
              site={{
                name: site?.name,
                filename: site?.filename,
                fileProofUrl: site?.fileProofUrl,
                address: site?.address,
                email: site?.email,
                phone: site?.phone
              }}
            >
              <SheetProvider>
                <SidebarProvider
                  style={
                    {
                      "--sidebar-width": "calc(var(--spacing) * 72)",
                      "--header-height": "calc(var(--spacing) * 12)",
                    } as React.CSSProperties
                  }
                >
                  <AppSidebar variant="inset" />
                  <SidebarInset>
                    <SiteHeader />
                    <div className="flex flex-1 flex-col">
                      <div className="@container/main flex flex-1 flex-col gap-2">
                        <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
                          <div className="px-4 lg:px-6">{children}</div>
                        </div>
                      </div>
                    </div>
                  </SidebarInset>
                </SidebarProvider>
              </SheetProvider>
            </SiteProvider>
          </ModalProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
